Js docx nv 1697
nhsengland/rap_intro_to_python pull request #7
Opened 2024-08-01 15:52 UTC by jenniferstruthers1-nhs

2024-08-05 09:19 UTC, warren-davies4 requested changes
This looks great Jen! I like how the session moves to using more complex examples that make use of the things learned in the previous ones, functions, loops and so on.

I made a couple of suggestions.

I think we've only touched on dictionaries so far, I wonder whether it's worth having a a short notebook before this one to more formally introduce them, and .items()/.values() etc. Or, we could just explain as we go. Just an idea - your call!

2024-08-05 09:19 UTC, warren-davies4 commented on README.md
> +**Workshop 4: Intro to PySpark**
thanks, sorry I forgot to add this!

2024-08-05 09:19 UTC, warren-davies4 commented on workshop_5/docx.ipynb
> +    "        if old_text in paragraph.text:\n",
here we could reduce nesting and intruduce `continue` with a guard clause:

```py
if old_text not in paragraph.text:
  continue

for run in...
```

2024-08-05 09:19 UTC, warren-davies4 commented on workshop_5/docx.ipynb
> +    "        doc = Document(template_docx)\n",
I think this declaration could be moved above the loop

2024-08-06 14:47 UTC, jenniferstruthers1-nhs commented
@warren-davies4 
I added a notebook on dictionaries, I think it's a good call as it might be a bit confusing to jump into them while learning something else new at the same time. It's fairly short but I think covers anything that would be necessary.

I didn't create any homework, but I think since we're supposed to be starting the thin slice that that will be enough

2024-08-07 08:55 UTC, warren-davies4 approved these changes
Great stuff, just fixed a typo or two

2024-08-07 08:55 UTC, warren-davies4 commented on workshop_5/dictionaries.ipynb
> +    "A dictionary in Python is an unordered collection of items. This is different from a list, where you can access the first, second, nth item. You cannot do this with dictionaries. Instead, each i
```suggestion
    "A dictionary in Python is an ordered collection of items. This is different from a list, where you can access the first, second, nth item. You cannot do this with dictionaries. Instead, each item is a key-value pair, where each key is unique and this is how you would access the 'value'.\n",
```

2024-08-07 08:55 UTC, warren-davies4 commented on workshop_5/dictionaries.ipynb
> +     "output_type": "stream",
did you mean to leave the outputs in?

2024-08-07 14:04 UTC, merged